## Deliverable 2. Create a Customer Travel Destinations Map.

In [47]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [48]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dikson,RU,73.5069,80.5464,42.22,93,100,25.23,overcast clouds
1,1,Hilo,US,19.7297,-155.0900,82.27,90,74,3.00,broken clouds
2,2,Ushuaia,AR,-54.8000,-68.3000,42.42,70,0,3.44,clear sky
3,3,Oxapampa,PE,-10.5775,-75.4017,67.24,78,88,2.77,overcast clouds
4,4,Saskylakh,RU,71.9167,114.0833,50.61,88,6,7.76,clear sky

In [49]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [51]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Hilo,US,19.7297,-155.0900,82.27,90,74,3.00,broken clouds
8,8,Hithadhoo,MV,-0.6000,73.0833,82.04,71,63,2.80,broken clouds
16,16,Lusambo,CD,-4.9667,23.4500,83.66,23,9,1.79,clear sky
19,19,Albany,US,42.6001,-73.9662,81.59,77,100,1.99,overcast clouds
28,28,Akhmeta,GE,42.0311,45.2075,79.32,54,46,0.96,scattered clouds
32,32,Aktau,KZ,43.6500,51.2000,79.38,42,39,18.63,scattered clouds
35,35,Kapaa,US,22.0752,-159.3190,76.12,85,75,14.97,broken clouds
39,39,Naze,JP,28.3667,129.4833,81.52,75,50,4.90,scattered clouds
41,41,Bengkulu,ID,-3.8004,102.2655,75.63,91,100,6.08,overcast clouds
44,44,Butaritari,KI,3.0707,172.7902,81.63,77,43,15.55,light rain

In [52]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                243
City                   243
Country                242
Lat                    243
Lng                    243
Max Temp               243
Humidity               243
Cloudiness             243
Wind Speed             243
Current Description    243
dtype: int64

In [53]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [54]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                242
City                   242
Country                242
Lat                    242
Lng                    242
Max Temp               242
Humidity               242
Cloudiness             242
Wind Speed             242
Current Description    242
dtype: int64

In [55]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Hilo,US,82.27,broken clouds,19.7297,-155.0900,
8,Hithadhoo,MV,82.04,broken clouds,-0.6000,73.0833,
16,Lusambo,CD,83.66,clear sky,-4.9667,23.4500,
19,Albany,US,81.59,overcast clouds,42.6001,-73.9662,
28,Akhmeta,GE,79.32,scattered clouds,42.0311,45.2075,
32,Aktau,KZ,79.38,scattered clouds,43.6500,51.2000,
35,Kapaa,US,76.12,broken clouds,22.0752,-159.3190,
39,Naze,JP,81.52,scattered clouds,28.3667,129.4833,
41,Bengkulu,ID,75.63,overcast clouds,-3.8004,102.2655,
44,Butaritari,KI,81.63,light rain,3.0707,172.7902,

In [56]:
# 6a. Set parameters to search for hotels with 5000 meters for philadelphia
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": "39.952583,-75.16522"
}
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
hotels_phi = requests.get(base_url, params=params)
hotels_phi.json()

{'html_attributions': [],
 'next_page_token': 'AeJbb3cZEetdDvdACKwEMBdvtFPdi7J85EtBm0iKDhfI1hN2aZwECGnGBEz0IZP3Gd-K3pWCYTILzSTGr9HWEvE5h4HJmPGDzxGOIo3u-OnLt0WA8i_AQD2s__bALHR-m1cC2jyVkrvZY6rNJfBpiIXNFtvCTWg_5tyovQo2OGXAuBriz6LzQVR3O2D92W7i14mN_-8dlacg3Tk2OFuA9Jthhz633jeic2fGiXh5OlZccSl-KXPxXDT5vRlSIloAEDyLgopBMGpOIO4m9jSeY7AutG0XpKTLqSYnFe4Ku_wmdL4pYNF7ozCGDWhbYknpi8aAapiruhBEk8wNMsrP2alEadbQueNxQyJ2ShHDi9ijgXkAFeOqPaAi6BuUxeZgl3vNfQfjFfC67xQim8u9pJg6uL7Ey3wqi-K_dyYS8gAeu58xNChejVSayVU7',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95144560000001, 'lng': -75.1641494},
    'viewport': {'northeast': {'lat': 39.9527542302915,
      'lng': -75.16273601970849},
     'southwest': {'lat': 39.9500562697085, 'lng': -75.1654339802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Ritz-Carlton, Philadelphia',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110307673324163831209">The Ritz-Carlton, Philadelphia</a>'],
     'photo_reference': 'AeJbb3eooj0FhtoaNLdSYCVEjufVi-AcnRVj_aRciH5as1DLDO03wgtjSBC2w7qmIUAQQwOwvm44zoVJ8WYhvPn-uwOUwpZcuPH-OQdGNW6CBlIaCsp6VVHw6nCu8LS364xPo-mdP_UL6xqvfAD_A-nVYwSKhcauwDQqsx8i9hLL0UGJzpIO',
     'width': 1366}],
   'place_id': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'plus_code': {'compound_code': 'XR2P+H8 Philadelphia, PA, USA',
    'global_code': '87F6XR2P+H8'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1919,
   'vicinity': '10 Avenue Of The Arts, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526485, 'lng': -75.1621109},
    'viewport': {'northeast': {'lat': 39.9539964302915,
      'lng': -75.1609723697085},
     'southwest': {'lat': 39.9512984697085, 'lng': -75.16367033029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Residence Inn by Marriott Philadelphia Center City',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114708714675201651378">Julie Nichols</a>'],
     'photo_reference': 'AeJbb3cd_IHjbvUejGne6DJcUgAEIThwQM00oLxArEm8ofkgPv6PDZCtROyX776CHVqzL1Lqs0ZUFO-EgcPrGLnWfDLJdtk86gE8yyfeHLuhzgf8qkChWX3G6304cizSjrAsRI17GcAsEMIF00ZQETXj1BeKJdHHVxecvLWPzp7zP4Cr6QRE',
     'width': 3024}],
   'place_id': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'plus_code': {'compound_code': 'XR3Q+35 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+35'},
   'rating': 4.2,
   'reference': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1288,
   'vicinity': 'One East Penn Square, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95486700000001,
     'lng': -75.16414139999999},
    'viewport': {'northeast': {'lat': 39.9560422802915,
      'lng': -75.1628017697085},
     'southwest': {'lat': 39.95334431970851, 'lng': -75.1654997302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Le Méridien Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104314711510842309587">Le Méridien Philadelphia</a>'],
     'photo_reference': 'AeJbb3cBlo1wOtEdyLsq01D3wSCP4fspoJ6F8u1IoLXhuY709GgETeO65aBqOWEdL5WD3y9Mc2u7YroJHi0lKM6a-yhbieP_eGRKj5szJdZBdxiTLigRv7d5Xwd5Uf7MOPQVguG7Z_vA1ym_6NHMCA0298HwVp4oge67Yyvl92CiArHR9oqY',
     'width': 1366}],
   'place_id': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'plus_code': {'compound_code': 'XR3P+W8 Philadelphia, PA, USA',
    'global_code': '87F6XR3P+W8'},
   'rating': 4.2,
   'reference': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1419,
   'vicinity': '1421 Arch Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9521123, 'lng': -75.1684916},
    'viewport': {'northeast': {'lat': 39.9534683302915,
      'lng': -75.1672094697085},
     'southwest': {'lat': 39.9507703697085, 'lng': -75.16990743029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Westin Philadelphia',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105705515475813455601">The Westin Philadelphia</a>'],
     'photo_reference': 'AeJbb3dpdE6YcAPHfbK4hUWNu_GMRWJtdWkUxWhaoPzkR_4LMvRTWadvSwdAZtjsOre4AhofRUbU7oNlJIAxclShUfSVAuUWiTqy6XCGpinfhrq5qU9rP5HR--L3gPmnVsOz7Z3rGus1iYQqb0843IK35_v8DalILNnLpWMVLTgu7jzKBls7',
     'width': 2048}],
   'place_id': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'plus_code': {'compound_code': 'XR2J+RJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+RJ'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 920,
   'vicinity': 'At, Liberty Place, 99 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95300650000001, 'lng': -75.1617435},
    'viewport': {'northeast': {'lat': 39.9543879302915,
      'lng': -75.16067606970849},
     'southwest': {'lat': 39.9516899697085, 'lng': -75.16337403029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Notary Hotel, Autograph Collection',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114199015026172908274">The Notary Hotel, Autograph Collection</a>'],
     'photo_reference': 'AeJbb3c9AM70WYRhDSpjOJbL3p9EMumJX8imdsuKdyTuKVH3LY56vf2Z9UXyzySZmDIDlDJVSB7TaNnI0z84Kv9f8vf5CbE-4eqvXQ8XdSNf53chBcS36XfhTNRMNpxtF4EI13vKsoHrREw54UXSme_SXU8GqVElDxxm0YGD1UDFUiglJTQA',
     'width': 2048}],
   'place_id': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'plus_code': {'compound_code': 'XR3Q+68 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+68'},
   'rating': 4.4,
   'reference': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2669,
   'vicinity': '21 North Juniper Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9512234, 'lng': -75.1684003},
    'viewport': {'northeast': {'lat': 39.9526733802915,
      'lng': -75.1670255197085},
     'southwest': {'lat': 39.9499754197085, 'lng': -75.16972348029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Club Quarters Hotel Rittenhouse Square, Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1356,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106194998780859366357">Club Quarters Hotel, Philadelphia, Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3fndL0m-9NsD_ZS2QGN0WBWDFpV9XfKLtGq4q33SnEFw35VuYLZ7D-4Fc5JJ8WhV9hVpQ_FmEI88n6K2O9gVp8q7fKzUdHSfTEfy3RqcBjyHOhjEvXMxhwICNP6uCG_M-wcmEcw4uZbyTSg2wexnwg68b6B3rZoFv5JwX0XUxT1-PlX',
     'width': 2048}],
   'place_id': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'plus_code': {'compound_code': 'XR2J+FJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+FJ'},
   'rating': 3.9,
   'reference': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2117,
   'vicinity': '1628 Chestnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95078150000001, 'lng': -75.1686419},
    'viewport': {'northeast': {'lat': 39.9521687302915,
      'lng': -75.16742716970849},
     'southwest': {'lat': 39.9494707697085, 'lng': -75.17012513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Kimpton Hotel Palomar Philadelphia',
   'photos': [{'height': 2138,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101918251476521929087">Kimpton Hotel Palomar Philadelphia</a>'],
     'photo_reference': 'AeJbb3fc9i5wKydEjMWKPCdiDFImgqo87QmtQ4cfra8VyUOBzxnZ6S7ZPFEKbEAxemwTr0_sseea-Dd8JBnf_9JFBTH30kHzVbIV58m0IVUFLZY9zOEcTohX_rpsC9thYoWau3OzVir8EVvODVin4ouXnCAQS0-dTHrpLzdW2hZs8T-6eDgv',
     'width': 3938}],
   'place_id': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'plus_code': {'compound_code': 'XR2J+8G Philadelphia, PA, USA',
    'global_code': '87F6XR2J+8G'},
   'price_level': 3,
   'rating': 4.5,
   'reference': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1427,
   'vicinity': '117 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95084739999999, 'lng': -75.1691058},
    'viewport': {'northeast': {'lat': 39.95221328029149,
      'lng': -75.1676571697085},
     'southwest': {'lat': 39.94951531970849, 'lng': -75.17035513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sofitel Philadelphia at Rittenhouse Square',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114227411825662988006">Hotel Sofitel Philadelphia at Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3cpN37jPX-dWQA6pJi4fpJ4AfpagggfPhxtgBr8neXYZA22WUTSykM5hB6gjkJzAlEHbXDUR_m0THvG_yVI3VKPVo_Jdy9kcmteKkRwJSPSC4IOIyDEukgXGY8n4vQEAZzawqLwb3mlfBFURSNcR68cQqGEqSpRhGUdWesLaW7RdOuh',
     'width': 5760}],
   'place_id': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'plus_code': {'compound_code': 'XR2J+89 Philadelphia, PA, USA',
    'global_code': '87F6XR2J+89'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2100,
   'vicinity': '120 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526035, 'lng': -75.16062459999999},
    'viewport': {'northeast': {'lat': 39.9537726802915,
      'lng': -75.15929566970848},
     'southwest': {'lat': 39.9510747197085, 'lng': -75.1619936302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Philadelphia Marriott Downtown',
   'photos': [{'height': 810,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113519425381372019862">Philadelphia Marriott Downtown</a>'],
     'photo_reference': 'AeJbb3eL434d6QN2vli7RldcUaH8bPWWJGQ_r_vvc4qq7gydzlG5OBXFWprgrg26Hpq73qa57yJ6Cck5Nc_vNMI-vPguUm0c1OrrzyToEu1dFPPUC5Zt8V5p78uCX0s-w_iDM4rtZ7AUAIC6qRL9Rss-rMb3bz2FCbHIRKpixAQqp2Pookv-',
     'width': 1440}],
   'place_id': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'plus_code': {'compound_code': 'XR3Q+2Q Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+2Q'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 6675,
   'vicinity': 'Guest Entrance At, 1201 Market Street, 1200 Filbert Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9557325, 'lng': -75.1681478},
    'viewport': {'northeast': {'lat': 39.95713563029149,
      'lng': -75.16665086970849},
     'southwest': {'lat': 39.95443766970849, 'lng': -75.16934883029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Windsor Suites',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109479920759808198512">The Windsor Suites</a>'],
     'photo_reference': 'AeJbb3fYejq0g5eokDf3pXULwZ640DEOfnwNuYmL6Azu7avo6fqMhOtj7foqX7ODPtd7n7xZ2sZJg82PT6KQ3JUlaKxsNYHXx5jCZX_j4upDdVAwUFXdzZXS-lS8bwC2HDtQGbMWspFKmCDUEbqaFXy3i-dbYnPvfpA5KiFMMvA-8FkyCQeb',
     'width': 5760}],
   'place_id': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'plus_code': {'compound_code': 'XR4J+7P Philadelphia, PA, USA',
    'global_code': '87F6XR4J+7P'},
   'rating': 4.1,
   'reference': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 650,
   'vicinity': '1700 Benjamin Franklin Parkway, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.949357, 'lng': -75.1623767},
    'viewport': {'northeast': {'lat': 39.9506045302915,
      'lng': -75.16121216970849},
     'southwest': {'lat': 39.9479065697085, 'lng': -75.1639101302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Holiday Inn Express Philadelphia-Midtown, an IHG Hotel',
   'photos': [{'height': 1526,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114795943691915946461">Holiday Inn Express Philadelphia-Midtown, an IHG Hotel</a>'],
     'photo_reference': 'AeJbb3eCP43IOH7Yn-lPoPc8GlS8RrIpHO3CVId80LbMisMoe5eYYBzkb-aWMCkyInI-MXmTte-Ge77sFlcYt9J-67552DeDaWRf4dJZdOgTMjc4gbi-FEmFCC9R8H5wp-4YK53KxolMKnmqoQtjvt3I84DbIy2q_s4MWi1ysADNuRPbiakD',
     'width': 2048}],
   'place_id': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'plus_code': {'compound_code': 'WRXQ+P2 Philadelphia, PA, USA',
    'global_code': '87F6WRXQ+P2'},
   'rating': 4.2,
   'reference': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1143,
   'vicinity': '1305 Walnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9515991, 'lng': -75.1602673},
    'viewport': {'northeast': {'lat': 39.9531279302915,
      'lng': -75.15890191970848},
     'southwest': {'lat': 39.9504299697085, 'lng': -75.1615998802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Loews Philadelphia Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1192,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111105514513926266494">Loews Philadelphia Hotel</a>'],
     'photo_reference': 'AeJbb3f5ODgsTpch_OvARcjqDo0yOvc8JLOutLg5PCsrRkXzx9UXmE0yQ5ArCRq20y4PE6XF_2IPZnjZrjWhLxfcuJfApj_diLnTxNSiucSxB21p6ha1h75AjKWEl3QwX3MPrkdnks5k1ohrE2NNx8DzKkPmGZK2c1fHCBo1KOAqLpFA3fEa',
     'width': 2120}],
   'place_id': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'plus_code': {'compound_code': 'XR2Q+JV Philadelphia, PA, USA',
    'global_code': '87F6XR2Q+JV'},
   'rating': 4.4,
   'reference': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4363,
   'vicinity': '1200 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9529083, 'lng': -75.1705983},
    'viewport': {'northeast': {'lat': 39.9544285802915,
      'lng': -75.16898036970848},
     'southwest': {'lat': 39.9517306197085, 'lng': -75.1716783302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sonesta Philadelphia Rittenhouse Square',
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117190836313501281895">Sonesta Philadelphia Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3cT0i9kchA_LuIyiHbDsmxKjPtc0F9XIcxR0RykxtfH7Z0Pb4O9Tg-Tl9RWm8WYWPaEYM5MDEmsRqrgM31Wdxwei1IvDKEg0B2kHzQ42SPRS3VNMM94z46dZhw4olCDYSG92-YBRDW6n7Ixuecr_8g0VmEQhvd9HCPsNQWYunCVer_n',
     'width': 1934}],
   'place_id': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'plus_code': {'compound_code': 'XR3H+5Q Philadelphia, PA, USA',
    'global_code': '87F6XR3H+5Q'},
   'rating': 4.2,
   'reference': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2432,
   'vicinity': '1800 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9479028, 'lng': -75.16403269999999},
    'viewport': {'northeast': {'lat': 39.94901273029149,
      'lng': -75.16297066970849},
     'southwest': {'lat': 39.94631476970849, 'lng': -75.1656686302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'DoubleTree by Hilton Hotel Philadelphia Center City',
   'photos': [{'height': 3137,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114457811229226481725">DoubleTree by Hilton Hotel Philadelphia Center City</a>'],
     'photo_reference': 'AeJbb3eIPA6pPgZ5VzJEDMdxNDqnFAHvbUJcbJecjQZArugMJ40mkOyDOvsxNc9Urkwi4VLcdhApq99ccIOpDEtSHp-ujWFvWi5I-e0slEEOAT1iFAw6VQEfduzQrpi3rReH-uBfJeXolXilgwV3RvWobZmgFIGMPuWpCCSTylWSMcQD5ONF',
     'width': 4851}],
   'place_id': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'plus_code': {'compound_code': 'WRXP+59 Philadelphia, PA, USA',
    'global_code': '87F6WRXP+59'},
   'rating': 4.2,
   'reference': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3719,
   'vicinity': '237 South Broad Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9562836, 'lng': -75.1607484},
    'viewport': {'northeast': {'lat': 39.9575507302915,
      'lng': -75.15931381970849},
     'southwest': {'lat': 39.9548527697085, 'lng': -75.16201178029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',

In [57]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [58]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Hilo,US,82.27,broken clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
8,Hithadhoo,MV,82.04,broken clouds,-0.6000,73.0833,Scoop Guest House
16,Lusambo,CD,83.66,clear sky,-4.9667,23.4500,
19,Albany,US,81.59,overcast clouds,42.6001,-73.9662,
28,Akhmeta,GE,79.32,scattered clouds,42.0311,45.2075,Hostel Kakheti
...,...,...,...,...,...,...,...
667,Jizan,SA,85.14,overcast clouds,17.3333,42.6667,شهدان. ابوالحجر
668,Warri,NG,79.34,overcast clouds,5.5167,5.7500,GT Guesthouse
670,Béboto,TD,76.32,broken clouds,8.2668,16.9390,
678,Kirakira,SB,77.74,overcast clouds,-10.4544,161.9205,SanBiz Lodge
684,Bosaso,SO,88.99,overcast clouds,11.2842,49.1816,Red Sea Hotel

In [59]:
# Replace empty cell with NaN
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)

In [60]:
hotel_df.count()

City                   242
Country                242
Max Temp               242
Current Description    242
Lat                    242
Lng                    242
Hotel Name             225
dtype: int64

In [61]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()

In [63]:
hotel_clean_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Hilo,US,82.27,broken clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
8,Hithadhoo,MV,82.04,broken clouds,-0.6000,73.0833,Scoop Guest House
28,Akhmeta,GE,79.32,scattered clouds,42.0311,45.2075,Hostel Kakheti
32,Aktau,KZ,79.38,scattered clouds,43.6500,51.2000,Silk Way Hotel
35,Kapaa,US,76.12,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort Hotel
39,Naze,JP,81.52,scattered clouds,28.3667,129.4833,Shishime Hotel
41,Bengkulu,ID,75.63,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
44,Butaritari,KI,81.63,light rain,3.0707,172.7902,Isles Sunset Lodge
45,George Town,MY,83.89,few clouds,5.4112,100.3354,Cititel Penang
47,Touros,BR,82.06,broken clouds,-5.1989,-35.4608,INN NEW HORIZON

In [64]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [65]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template =  """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]

In [46]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))