## Deliverable 2. Create a Customer Travel Destinations Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ganzhou,CN,28.8184,115.4327,100.42,41,55,8.70,broken clouds
1,1,Padang,ID,-0.9492,100.3543,86.05,62,42,6.87,scattered clouds
2,2,Ballina,AU,-28.8667,153.5667,69.01,41,9,3.53,clear sky
3,3,São João da Barra,BR,-21.6403,-41.0511,70.14,84,97,9.31,overcast clouds
4,4,Cape Town,ZA,-33.9258,18.4232,55.11,87,0,3.44,clear sky

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Padang,ID,-0.9492,100.3543,86.05,62,42,6.87,scattered clouds
12,12,Vaini,TO,-21.2000,-175.2000,77.16,100,40,5.75,scattered clouds
15,15,Nagornskiy,RU,58.7731,57.5451,77.86,46,27,4.97,scattered clouds
21,21,Russell,US,32.3502,-85.1999,76.01,79,41,3.47,scattered clouds
24,24,Mahébourg,MU,-20.4081,57.7000,75.25,73,40,11.50,scattered clouds
26,26,Garoowe,SO,8.4054,48.4845,79.30,44,51,27.40,broken clouds
27,27,Dakar,SN,14.6937,-17.4441,77.88,82,96,6.33,light rain
28,28,Puerto Escondido,MX,15.8500,-97.0667,78.46,88,98,4.07,overcast clouds
33,33,Katsuura,JP,35.1333,140.3000,83.57,79,29,9.75,scattered clouds
35,35,Atuona,PF,-9.8000,-139.0333,77.27,73,22,18.97,few clouds

In [9]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                200
City                   200
Country                200
Lat                    200
Lng                    200
Max Temp               200
Humidity               200
Cloudiness             200
Wind Speed             200
Current Description    200
dtype: int64

In [10]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [11]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                200
City                   200
Country                200
Lat                    200
Lng                    200
Max Temp               200
Humidity               200
Cloudiness             200
Wind Speed             200
Current Description    200
dtype: int64

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Padang,ID,86.05,scattered clouds,-0.9492,100.3543,
12,Vaini,TO,77.16,scattered clouds,-21.2000,-175.2000,
15,Nagornskiy,RU,77.86,scattered clouds,58.7731,57.5451,
21,Russell,US,76.01,scattered clouds,32.3502,-85.1999,
24,Mahébourg,MU,75.25,scattered clouds,-20.4081,57.7000,
26,Garoowe,SO,79.30,broken clouds,8.4054,48.4845,
27,Dakar,SN,77.88,light rain,14.6937,-17.4441,
28,Puerto Escondido,MX,78.46,overcast clouds,15.8500,-97.0667,
33,Katsuura,JP,83.57,scattered clouds,35.1333,140.3000,
35,Atuona,PF,77.27,few clouds,-9.8000,-139.0333,

In [19]:
# 6a. Set parameters to search for hotels with 5000 meters for philadelphia
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": "39.952583,-75.16522"
}
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
hotels_phi = requests.get(base_url, params=params)
hotels_phi.json()

{'html_attributions': [],
 'next_page_token': 'AeJbb3fDNonYVUMYeNRpzWirF_ErJGH2hyqLYuZ114_FqPIp3EsXWM48xR_i-8prr5GjNlpLtyqI8vZhshsHKXYv1lYZgqjdvYRHQv5AjSx8107pBUMv1Ixnamp-L0At8jubEYG_kGwzU_U1f6fTv87-9OZEDdnZjRW_GwKetBz9xwrxMgvOg5QOWuamiZmDqqEUp7GaYXbJC6zBlUWZBvvpuGM3oy6_T1Ga32qVbRIq1nTM4qHbad1iQfmv4HLC70YG8bjqaYf6fAmUzV5t4A2foG3FGvm-Gtnz8s9UPM8l6E4Qi0B2KJa70awTFzQcdSlN1LOw5yvfhV8V0UUrzQrSKTiZLTX45APhs2WjjFMa2F69QL0BAyYxUAsHECan_nPSoL7zw5VT72HqyKGWSFKP0AzZZyXU8i4WzPEM-jhbAHpSdqXqstOar4o6',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95144560000001, 'lng': -75.1641494},
    'viewport': {'northeast': {'lat': 39.9527542302915,
      'lng': -75.16273601970849},
     'southwest': {'lat': 39.9500562697085, 'lng': -75.1654339802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Ritz-Carlton, Philadelphia',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110307673324163831209">The Ritz-Carlton, Philadelphia</a>'],
     'photo_reference': 'AeJbb3fsfA14-E8UKad0_4lRRG5lcVEEaCvbtn3miP1ALjFMMyeQHjut7OG3Zup1DRkUD734YwgHgvPbhEmP_grdtkOsmJQfpV_Fk9CDZuqM-oWFsPVrzP1bB4fe9JCl6C_bP7JJjbPfqHUM7dB1uE_NaOIj8bScqTJrjJNPTA42rmlsTrT3',
     'width': 1366}],
   'place_id': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'plus_code': {'compound_code': 'XR2P+H8 Philadelphia, PA, USA',
    'global_code': '87F6XR2P+H8'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJv51-sC_GxokR6fV5EFtVIyc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1919,
   'vicinity': '10 Avenue Of The Arts, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526485, 'lng': -75.1621109},
    'viewport': {'northeast': {'lat': 39.9539964302915,
      'lng': -75.1609723697085},
     'southwest': {'lat': 39.9512984697085, 'lng': -75.16367033029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Residence Inn by Marriott Philadelphia Center City',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114708714675201651378">Julie Nichols</a>'],
     'photo_reference': 'AeJbb3faqW8GfsOv9Zhcix3DJmTZXO-N4dFCThZUctbKdalR0_OsrIaHVJ-CFRmw_kZS474jcLXGsx_Wc0OOCgC_lUwHTbcSN_giw8o4qq26o011vEU5dfPVYWH1MNpV7P-dG4BuLwy9wc1e0X2KLHj6huydon_hUAp0TTLonknKe1xwOAqZ',
     'width': 3024}],
   'place_id': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'plus_code': {'compound_code': 'XR3Q+35 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+35'},
   'rating': 4.2,
   'reference': 'ChIJdTu_7S7GxokR97kxJyXerfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1287,
   'vicinity': 'One East Penn Square, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95486700000001,
     'lng': -75.16414139999999},
    'viewport': {'northeast': {'lat': 39.9560422802915,
      'lng': -75.1628017697085},
     'southwest': {'lat': 39.95334431970851, 'lng': -75.1654997302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Le Méridien Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104314711510842309587">Le Méridien Philadelphia</a>'],
     'photo_reference': 'AeJbb3dUN7EzdITtKWQLwNSzzyEvHLOiZp9nKqnsbjGMDyV1Cvabvttq2bA1crT1hRYhheAsIiQT-aRAgLrwBy9VVXCkThpdWYPJ97UP1fx6ZboAv8LEXBShDvnhxipwf1QiKSTDcFPI6YkfUf7LBOUg0_yMvAK4GMDd2iRKgA_33qioUZC_',
     'width': 1366}],
   'place_id': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'plus_code': {'compound_code': 'XR3P+W8 Philadelphia, PA, USA',
    'global_code': '87F6XR3P+W8'},
   'rating': 4.2,
   'reference': 'ChIJNyI72i3GxokRbboLZHgUf_8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1419,
   'vicinity': '1421 Arch Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9521123, 'lng': -75.1684916},
    'viewport': {'northeast': {'lat': 39.9534683302915,
      'lng': -75.1672094697085},
     'southwest': {'lat': 39.9507703697085, 'lng': -75.16990743029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Westin Philadelphia',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105705515475813455601">The Westin Philadelphia</a>'],
     'photo_reference': 'AeJbb3eX11uT_zpN6SDBVGgS91s3LKmiIjvjDXFnY8fiL3iPgSxpfx0Rc6m6ttdSOXMfZ-2jy0O6vSgXLegVJd9txm5rizIWCo4r1hBZfO04m27mWHmbQS1rzER6YcGIOuP7PQYvu0IMoTwYKrKMIEc8i0UDgl7ujHL5O08QTk-CoAFzMWUn',
     'width': 2048}],
   'place_id': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'plus_code': {'compound_code': 'XR2J+RJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+RJ'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJ6_1xXDDGxokRIQqqKZGjCNg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 920,
   'vicinity': 'At, Liberty Place, 99 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95300650000001, 'lng': -75.1617435},
    'viewport': {'northeast': {'lat': 39.9543879302915,
      'lng': -75.16067606970849},
     'southwest': {'lat': 39.9516899697085, 'lng': -75.16337403029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Notary Hotel, Autograph Collection',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114199015026172908274">The Notary Hotel, Autograph Collection</a>'],
     'photo_reference': 'AeJbb3cOriA0SZKOagT9FCnXDGQrxKl0BV35ErlGQ9t-3npYF3ZOSSHnDGSZJunjNLuxjxJ_0usuZqlsgDaMRVS6hpEYsWf_sNHK00C0i-Lpz4bZXZQrGSuVSVg7mM6i4bYd6u2ynpQkJBMPbuo0GmIoP2FP5T3eSQteeYUZ3H18A-oIXs6K',
     'width': 2048}],
   'place_id': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'plus_code': {'compound_code': 'XR3Q+68 Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+68'},
   'rating': 4.4,
   'reference': 'ChIJkWOsky7GxokRRVwy9AGBEDU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2665,
   'vicinity': '21 North Juniper Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9512234, 'lng': -75.1684003},
    'viewport': {'northeast': {'lat': 39.9526733802915,
      'lng': -75.1670255197085},
     'southwest': {'lat': 39.9499754197085, 'lng': -75.16972348029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Club Quarters Hotel Rittenhouse Square, Philadelphia',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1356,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106194998780859366357">Club Quarters Hotel, Philadelphia, Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3faz1-7nlu2CsbY2NDdCnVsHHT8UAq_OZy1m-lX6vU5vKAOhgb1p-1pGSb6rUePM7R_YZsxatDIDf7L2f9fIY0if4flgTwWDOCjyHtLxSivIyGqQv7BWFiH_Oje2ub4X-md9Il1_lE-9XtNSXbrJBsbplLNpAiG6TH8BL0r50wbDTY2',
     'width': 2048}],
   'place_id': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'plus_code': {'compound_code': 'XR2J+FJ Philadelphia, PA, USA',
    'global_code': '87F6XR2J+FJ'},
   'rating': 3.9,
   'reference': 'ChIJUXdDXDDGxokR9rLmamBhX88',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2117,
   'vicinity': '1628 Chestnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95078150000001, 'lng': -75.1686419},
    'viewport': {'northeast': {'lat': 39.9521687302915,
      'lng': -75.16742716970849},
     'southwest': {'lat': 39.9494707697085, 'lng': -75.17012513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Kimpton Hotel Palomar Philadelphia',
   'photos': [{'height': 2138,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101918251476521929087">Kimpton Hotel Palomar Philadelphia</a>'],
     'photo_reference': 'AeJbb3chIB247o4VXPhV9ndrR-nfIfNhPE8Pt2RYXD25hUfHwxrcRk_YDy-N80B9oNSJexAD1tw_Ys4VnjtlCgZMEDjNgR77HZGTtU81_RkSDnFRorpFUjA_K9qiZ_v_f2nBxtnvMNL5XgzFw_6JumWjbUcuuB9-vFrrg7nFRicoeO1PPWHo',
     'width': 3938}],
   'place_id': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'plus_code': {'compound_code': 'XR2J+8G Philadelphia, PA, USA',
    'global_code': '87F6XR2J+8G'},
   'price_level': 3,
   'rating': 4.5,
   'reference': 'ChIJD55aYTDGxokRuW1PyOVzdxQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1424,
   'vicinity': '117 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.95084739999999, 'lng': -75.1691058},
    'viewport': {'northeast': {'lat': 39.95221328029149,
      'lng': -75.1676571697085},
     'southwest': {'lat': 39.94951531970849, 'lng': -75.17035513029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sofitel Philadelphia at Rittenhouse Square',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114227411825662988006">Hotel Sofitel Philadelphia at Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3cgBR-C3io3NOaE9WWpfudjTgDMFmSe7FAuU4t-yzOPi1ISWAs35TOwptmLZelx2BRNQmF7HskiJOS7QxAFSxkBi0lNoa5Gmz5ExZDLfs7kjbgHg0ED01rhxqntvKHAdYpJwBmOql1kTn3u6mMRWRq201OkBXt8zV1Inh2OaCVUQ6cU',
     'width': 5760}],
   'place_id': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'plus_code': {'compound_code': 'XR2J+89 Philadelphia, PA, USA',
    'global_code': '87F6XR2J+89'},
   'price_level': 3,
   'rating': 4.4,
   'reference': 'ChIJrQbSYzDGxokR2TCy3fjNWoQ',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 2100,
   'vicinity': '120 South 17th Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9526035, 'lng': -75.16062459999999},
    'viewport': {'northeast': {'lat': 39.9537726802915,
      'lng': -75.15929566970848},
     'southwest': {'lat': 39.9510747197085, 'lng': -75.1619936302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Philadelphia Marriott Downtown',
   'photos': [{'height': 810,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113519425381372019862">Philadelphia Marriott Downtown</a>'],
     'photo_reference': 'AeJbb3deotWWE7BDPoD1eDCPbU00WK038J3PdGC7q3-5DvOn_phCghQ6hAzhRh4vbeFFyUf5UCiumhse_9AY_wuli6_yo7EFzK21suTWJh_hOEbgHqQG6CwzI6f42Z7WHFtcI05_N7lh0NXRYvf0nBZzxl0oAkGqlKg_NEKM-OFOtSwyT3LE',
     'width': 1440}],
   'place_id': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'plus_code': {'compound_code': 'XR3Q+2Q Philadelphia, PA, USA',
    'global_code': '87F6XR3Q+2Q'},
   'price_level': 3,
   'rating': 4.2,
   'reference': 'ChIJOx8izC7GxokRPvOWsXcBRXs',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 6672,
   'vicinity': 'Guest Entrance At, 1201 Market Street, 1200 Filbert Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9557325, 'lng': -75.1681478},
    'viewport': {'northeast': {'lat': 39.95713563029149,
      'lng': -75.16665086970849},
     'southwest': {'lat': 39.95443766970849, 'lng': -75.16934883029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'The Windsor Suites',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109479920759808198512">The Windsor Suites</a>'],
     'photo_reference': 'AeJbb3fJUlJjmnxZq3SQ0-vE8MCU-adPJK9WWL8mairxLZZ3FJOiMyozTJEHFnQ1FhgcbBecKspanmq46PZ7tZibUTx5xfQVSkgP3wrhYKMZEAH4eKNINQHqOJPrE4GucovMnJz-CAiLnIt5LF8LDfEVSVbUQGR4fqE7cubkX2ENSXk5Cy9D',
     'width': 5760}],
   'place_id': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'plus_code': {'compound_code': 'XR4J+7P Philadelphia, PA, USA',
    'global_code': '87F6XR4J+7P'},
   'reference': 'ChIJdVCkPzLGxokRZYFGa7RAGlc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '1700 Benjamin Franklin Parkway, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.949357, 'lng': -75.1623767},
    'viewport': {'northeast': {'lat': 39.9506045302915,
      'lng': -75.16121216970849},
     'southwest': {'lat': 39.9479065697085, 'lng': -75.1639101302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Holiday Inn Express Philadelphia-Midtown, an IHG Hotel',
   'photos': [{'height': 1526,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114795943691915946461">Holiday Inn Express Philadelphia-Midtown, an IHG Hotel</a>'],
     'photo_reference': 'AeJbb3cwmZ6EI15HlB-GrLUix1gl2m_v97IMXDBaPWAI183oTpLFuGW7PW07JbE3uPIrNk_EAgjq0JBXhmUcCDdO3Q6YxfTnmQoeVHp2q_GamurE1nXt4jSHHcta3xt4AlyzOwMQZkmjYlt3BA8nZwGFzzlQzp05935SoIaHqJZ6dB1fsT0l',
     'width': 2048}],
   'place_id': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'plus_code': {'compound_code': 'WRXQ+P2 Philadelphia, PA, USA',
    'global_code': '87F6WRXQ+P2'},
   'rating': 4.2,
   'reference': 'ChIJj7NcYi_GxokRN-XxX1zeGsQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1142,
   'vicinity': '1305 Walnut Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9515991, 'lng': -75.1602673},
    'viewport': {'northeast': {'lat': 39.9531279302915,
      'lng': -75.15890191970848},
     'southwest': {'lat': 39.9504299697085, 'lng': -75.1615998802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Loews Philadelphia Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1192,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111105514513926266494">Loews Philadelphia Hotel</a>'],
     'photo_reference': 'AeJbb3e8Wcgq3MU0WlVQpuoMGPVsxgI4H_NiWxcLnFVWHhsKtyItha-DcfJtF7h_Z4YHWY_8cj3vdWR5pAapZIWBlIFRjPtubS7PofQNvT9-p-wz5oa2-LJiDJJe-CVnVCtm_SyDoEQJzYw-fv9VqiRUaaxdoXOEaWSarOgrEx5BANZJ9g-b',
     'width': 2120}],
   'place_id': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'plus_code': {'compound_code': 'XR2Q+JV Philadelphia, PA, USA',
    'global_code': '87F6XR2Q+JV'},
   'rating': 4.4,
   'reference': 'ChIJ6bNuLSnGxokR29Oj-g9Tojo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4361,
   'vicinity': '1200 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9529083, 'lng': -75.1705983},
    'viewport': {'northeast': {'lat': 39.9544285802915,
      'lng': -75.16898036970848},
     'southwest': {'lat': 39.9517306197085, 'lng': -75.1716783302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sonesta Philadelphia Rittenhouse Square',
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117190836313501281895">Sonesta Philadelphia Rittenhouse Square</a>'],
     'photo_reference': 'AeJbb3dv8mb4P2ef_vvWa-Boc9TSCmNUSp-gS8dW8JiwliYS0LrdCQqyzZUxsNWRCWLgB6N3lotOhfMwkKHGjppMHxchPb6hhdNZC6ohTF8-UtOAAu2FNjLsXrihcurW52zXM82FfZ8ZWnY4kEgPyj0nN7S8tzeb5nTKkzQ_4EBaQDJ5JUic',
     'width': 1934}],
   'place_id': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'plus_code': {'compound_code': 'XR3H+5Q Philadelphia, PA, USA',
    'global_code': '87F6XR3H+5Q'},
   'reference': 'ChIJS-B6GTHGxokRtXWy8SVZiM4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '1800 Market Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9479028, 'lng': -75.16403269999999},
    'viewport': {'northeast': {'lat': 39.94901273029149,
      'lng': -75.16297066970849},
     'southwest': {'lat': 39.94631476970849, 'lng': -75.1656686302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'DoubleTree by Hilton Hotel Philadelphia Center City',
   'photos': [{'height': 3137,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114457811229226481725">DoubleTree by Hilton Hotel Philadelphia Center City</a>'],
     'photo_reference': 'AeJbb3d09Fwag-X2iuMQKNUYSLtMDvMi6cWnkvhLQj1o1aJDODRnp_9SKglv6inyMl4OaBzoQRqt_b79mb1h1i9TuSu1ciFcdpaIEwhH9JkL675F6MqRY9nlNUqOv47637IWgpA6jWmwhkCxMTLHCDHZ-e7hj1WqnF8wq9nLbZC9FtkocXhv',
     'width': 4851}],
   'place_id': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'plus_code': {'compound_code': 'WRXP+59 Philadelphia, PA, USA',
    'global_code': '87F6WRXP+59'},
   'rating': 4.2,
   'reference': 'ChIJQ433EiXGxokRnWqMZZoUCDo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3719,
   'vicinity': '237 South Broad Street, Philadelphia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 39.9562836, 'lng': -75.1607484},
    'viewport': {'northeast': {'lat': 39.9575507302915,
      'lng': -75.15931381970849},
     'southwest': {'lat': 39.9548527697085, 'lng': -75.16201178029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',

In [20]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [13]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Padang,ID,86.05,scattered clouds,-0.9492,100.3543,
12,Vaini,TO,77.16,scattered clouds,-21.2000,-175.2000,
15,Nagornskiy,RU,77.86,scattered clouds,58.7731,57.5451,
21,Russell,US,76.01,scattered clouds,32.3502,-85.1999,
24,Mahébourg,MU,75.25,scattered clouds,-20.4081,57.7000,
...,...,...,...,...,...,...,...
547,Bouza,NE,78.91,scattered clouds,14.4229,6.0428,
550,Karpathos,GR,78.76,few clouds,35.5070,27.2132,
551,Klyuchi,RU,80.58,clear sky,52.2667,79.1667,
552,Anzio,IT,83.86,few clouds,41.4853,12.6179,
561,Kampong Thom,KH,79.81,overcast clouds,12.7111,104.8887,

In [14]:
# Replace empty cell with NaN
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)

In [15]:
hotel_df.count()

City                   200
Country                200
Max Temp               200
Current Description    200
Lat                    200
Lng                    200
Hotel Name               0
dtype: int64

In [16]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()

In [17]:
hotel_clean_df.head(10)

Empty DataFrame
Columns: [City, Country, Max Temp, Current Description, Lat, Lng, Hotel Name]
Index: []

In [22]:
# 8a. Create the output File (CSV)
output_data_file = "unit4.csv"
# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index=False, header=True)

In [45]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template =  """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]

In [46]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))